name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: rustup target add thumbv6m-none-eabi
    - name: Build
      run: cargo build --verbose

  build-cargo-update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: rustup target add thumbv6m-none-eabi
    - name: Update Dependencies
      run: cargo update
    - name: Build
      run: cargo build --verbose
